//local host
//all contacts
GET http://localhost:3000/contacts

//by ID
###
GET http://localhost:3000/contacts/644df33583495acbe62b9027

###
GET http://localhost:3000/contacts/644df34f83495acbe62b9029

###
GET http://localhost:3000/contacts/644df35d83495acbe62b902b

//Render
//all conacts
###
GET https://cse341-lesson2-2iya.onrender.com/contacts

//by ID
###
GET https://cse341-lesson2-2iya.onrender.com/contacts/644df33583495acbe62b9027

###
GET https://cse341-lesson2-2iya.onrender.com/contacts/644df34f83495acbe62b9029

###
GET https://cse341-lesson2-2iya.onrender.com/contacts/644df35d83495acbe62b902b

//Post/Create new conact
###
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Megan",
    "lastName": "Jankiewicz",
    "email": "megjankiewicz@hotmail.com",
    "favoriteColor": "light pink",
    "birthday": "February 26, 1989"
}

//Put/edit contact
###
PUT http://localhost:3000/contacts/644df33583495acbe62b9027 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mason",
    "lastName": "Jankiewicz",
    "email": "masonjankiewicz@gmail.com",
    "favoriteColor": "blue",
    "birthday": "August 5, 2015"
}
//delete contact
###
DELETE http://localhost:3000/contacts/64570b78f704b829c9a58b2e HTTP/1.1